"""Build the reviewed Census-to-OCD crosswalk for state legislative districts that have no shared code.

Census codes most districts with a number that OpenStates (Open Civic Data) also uses, and
``link_divisions.sql`` joins those by code. Five places do not share a code: the Massachusetts
House and Senate, the New Hampshire House (its Senate uses plain numbers), Vermont's House and Senate, the District of Columbia
wards and Puerto Rico's two chambers. Census names each of their districts; OCD writes the
same district as a slug of that name (``1st Barnstable District`` -> ``1st_barnstable``).

This script derives each OCD id from the official Census district name with the explicit
rules below, then refuses to write the file unless every check passes:

* the id is in the pinned official OCD list (``opencivicdata/ocd-division-ids``);
* no two Census districts share an id;
* the id is a division in the OpenStates snapshot (``openstates_source``);
* any id the OCD list marks as ended, or that OpenStates holds no seat for, is named in
  ``EXCEPTIONS`` with the evidence for accepting it.

The linker reads the written file by identifier only. Run:
``uv run python scripts/build_ocd_sld_crosswalk.py``.
"""

from __future__ import annotations

import csv
import hashlib
import re
import sys
import urllib.request
from collections import Counter
from pathlib import Path

from opendiscourse_research.db import connect

OCD_COMMIT = "1ec1eda010addd54412f5491d8d695303189e354"
OCD_FILES = {
    "us_sldl.csv": "28159c54c269bc95d633193c43390342ff27541ca28c59dbfd865f862dc3d2ff",
    "us_sldu.csv": "9e4a546222c5fc9bded816e93ed73ee4a1701ab488a08495cb601c546e25f185",
}
OCD_URL = (
    "https://raw.githubusercontent.com/opencivicdata/ocd-division-ids/{commit}"
    "/identifiers/country-us/census_autogenerated/{name}"
)
OUTPUT = Path(__file__).resolve().parents[1] / "inventory" / "geography" / "ocd-sld-crosswalk-2024.csv"
STATES = ("11", "25", "33", "50", "72")  # DC, MA, NH, VT, PR

#: Census state FIPS the rules below handle, and the chamber of each.
ORDINAL_WORDS = {"first": "1st", "second": "2nd", "third": "3rd", "fourth": "4th", "fifth": "5th"}

#: Pairs where the derived id is accepted although a check would otherwise fail, with the evidence.
EXCEPTIONS: dict[tuple[str, str], str] = {
    ("sldl", "50ORC"): (
        "OCD marks sldl:orange-caledonia ended 2023-01-03, but the 2024 Census file lists Orange-Caledonia "
        "and OpenStates holds a seat on that division"
    ),
    ("sldl", "50WWB"): (
        "OpenStates has no division sldl:windham-windsor-bennington; it holds the seat on "
        "sldl:windham-bennington-windsor with post label Windham-Windsor-Bennington, so members attach there. "
        "OCD marks that id ended 2023-01-03"
    ),
}
#: Names whose OCD spelling is not a mechanical slug; each is checked by the same gates.
OVERRIDES: dict[tuple[str, str], str] = {
    ("sldl", "50WWB"): "state:vt/sldl:windham-bennington-windsor",
    ("sldl", "50GIC"): "state:vt/sldl:grand_isle-chittenden",
    ("sldu", "50CHC"): "state:vt/sldu:chittenden-central",
    ("sldu", "50CHN"): "state:vt/sldu:chittenden-north",
    ("sldu", "50CHS"): "state:vt/sldu:chittenden-southeast",
}
PREFIX = "ocd-division/country:us/"


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")


def joined_list(text: str) -> str:
    """``A-B-C`` -> ``a_b_and_c``: how OCD writes a district named for several counties."""
    parts = text.split("-")
    return slug(parts[0]) if len(parts) == 1 else "_".join(slug(p) for p in parts[:-1]) + "_and_" + slug(parts[-1])


def derive(chamber: str, geoid: str, name: str) -> str:
    """OCD id (without the common prefix) for one Census district, from its official name."""
    state, code = geoid[:2], geoid[2:]
    if (chamber, geoid) in OVERRIDES:
        return OVERRIDES[(chamber, geoid)]
    if state == "11":
        return f"district:dc/ward:{int(code)}"
    if state == "72":
        return f"territory:pr/{chamber}:{int(code)}"
    if state == "25" and chamber == "sldl":
        m = re.fullmatch(r"(?:(\d+)(st|nd|rd|th) )?(.+) District", name)
        assert m, name
        return "state:ma/sldl:" + (f"{m[1]}{m[2]}_" if m[1] else "") + joined_list(m[3])
    if state == "25":
        out = "state:ma/sldu:" + joined_list(re.sub(r" District$", "", name))
        for word, short in ORDINAL_WORDS.items():
            out = out.replace(f"sldu:{word}_", f"sldu:{short}_")
        return out
    if state == "33" and chamber == "sldl":
        m = re.fullmatch(r"State House District (\w+) (\d+)", name)
        assert m, name
        return f"state:nh/sldl:{m[1].lower()}_{int(m[2])}"
    if state == "50" and chamber == "sldl":
        m = re.fullmatch(r"(.+) State House District", name)
        assert m, name
        return "state:vt/sldl:" + slug(m[1]).replace("_", "-")
    if state == "50":
        m = re.fullmatch(r"(.+) Senatorial District", name)
        assert m, name
        return "state:vt/sldu:" + slug(m[1])
    raise ValueError(f"no rule for {chamber} {geoid} {name!r}")


def fetch_ocd() -> dict[str, tuple[str, str]]:
    """Pinned official OCD lists, verified by checksum: id -> (valid_from, valid_through)."""
    found: dict[str, tuple[str, str]] = {}
    for name, expected in OCD_FILES.items():
        body = urllib.request.urlopen(OCD_URL.format(commit=OCD_COMMIT, name=name), timeout=60).read()
        if hashlib.sha256(body).hexdigest() != expected:
            raise SystemExit(f"{name}: checksum differs from the reviewed one; re-review before updating")
        for row in csv.DictReader(body.decode().splitlines()):
            found[row["id"]] = (row["validFrom"], row["validThrough"])
    return found


def main() -> int:
    ocd = fetch_ocd()
    with connect() as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT DISTINCT layer, geoid, name FROM stage.tiger_feature "
            "WHERE layer IN ('sldl','sldu') AND state_fips = ANY(%s) AND geoid !~ 'ZZZ' AND NOT (state_fips = '33' AND layer = 'sldu') ORDER BY 1, 2",
            (list(STATES),),
        )
        census = [(r["layer"], r["geoid"], r["name"]) for r in cur.fetchall()]
        cur.execute("SELECT id FROM openstates_source.opencivicdata_division")
        openstates_divisions = {r["id"] for r in cur.fetchall()}
        cur.execute(
            "SELECT DISTINCT division_id FROM openstates_source.opencivicdata_post"
        )
        seated = {r["division_id"] for r in cur.fetchall()}

    rows, problems = [], []
    for chamber, geoid, name in census:
        full = PREFIX + derive(chamber, geoid, name)
        notes = []
        if full not in ocd:
            problems.append(f"{chamber} {geoid} {name!r}: {full} is not in the official OCD list")
            continue
        if ocd[full][1]:
            notes.append(f"OCD valid through {ocd[full][1]}")
        if full not in openstates_divisions:
            problems.append(f"{chamber} {geoid}: {full} is not an OpenStates division")
        if full not in seated:
            notes.append("no OpenStates seat on this division")
        if notes and (chamber, geoid) not in EXCEPTIONS:
            problems.append(f"{chamber} {geoid} {name!r}: {full}: {'; '.join(notes)} (not a reviewed exception)")
        rows.append((geoid, chamber, full, name, EXCEPTIONS.get((chamber, geoid), "")))
    for ocd_id, count in Counter(r[2] for r in rows).items():
        if count > 1:
            problems.append(f"{ocd_id} is claimed by {count} Census districts")
    if problems:
        print("\n".join(problems), file=sys.stderr)
        return 1
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(["census_geoid", "chamber", "ocd_division_id", "census_name", "exception_evidence"])
        writer.writerows(sorted(rows))
    print(f"wrote {len(rows)} reviewed pairs to {OUTPUT} (OCD commit {OCD_COMMIT})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
